"""Add time_taken to Assessment

Revision ID: b7eb008d0253
Revises: fb68b15b485f
Create Date: 2025-08-08 06:38:11.520339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eb008d0253'
down_revision = 'fb68b15b485f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('time_taken')

    # ### end Alembic commands ###
